<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="delivery_bot">

  <!-- ==================== PROPERTIES ==================== -->
  <xacro:property name="chassis_length" value="0.5"/>
  <xacro:property name="chassis_width" value="0.3"/>
  <xacro:property name="chassis_height" value="0.15"/>
  <xacro:property name="chassis_mass" value="10.0"/>
  
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_mass" value="0.5"/>
  
  <xacro:property name="lidar_size" value="0.05"/>
  <xacro:property name="camera_size" value="0.03"/>
  
  <!-- Wheel positions -->
  <xacro:property name="wheel_x_offset" value="0.15"/>
  <xacro:property name="wheel_y_offset" value="0.17"/>
  <xacro:property name="wheel_z_offset" value="-0.04"/>

  <!-- ==================== MATERIALS ==================== -->
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.1 0.1 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <!-- ==================== INERTIA MACROS ==================== -->
  <xacro:macro name="box_inertia" params="m x y z">
    <inertia ixx="${(m/12)*(y*y+z*z)}" ixy="0" ixz="0"
             iyy="${(m/12)*(x*x+z*z)}" iyz="0"
             izz="${(m/12)*(x*x+y*y)}"/>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${(m/12)*(3*r*r+h*h)}" ixy="0" ixz="0"
             iyy="${(m/12)*(3*r*r+h*h)}" iyz="0"
             izz="${(m/2)*r*r}"/>
  </xacro:macro>

  <!-- ==================== WHEEL MACRO ==================== -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_reflect * wheel_x_offset} ${y_reflect * wheel_y_offset} ${wheel_z_offset}" 
              rpy="${-pi/2} 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2" friction="0.3"/>
    </joint>
  </xacro:macro>

  <!-- ==================== BASE LINK ==================== -->
  <link name="base_footprint"/>
  
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <xacro:box_inertia m="${chassis_mass}" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}"/>
    </inertial>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius - wheel_z_offset}" rpy="0 0 0"/>
  </joint>

  <!-- ==================== WHEELS ==================== -->
  <xacro:wheel prefix="front_left" x_reflect="1" y_reflect="1"/>
  <xacro:wheel prefix="front_right" x_reflect="1" y_reflect="-1"/>
  <xacro:wheel prefix="rear_left" x_reflect="-1" y_reflect="1"/>
  <xacro:wheel prefix="rear_right" x_reflect="-1" y_reflect="-1"/>

  <!-- ==================== LIDAR SENSOR ==================== -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_size}" length="${lidar_size}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_size}" length="${lidar_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <xacro:cylinder_inertia m="0.1" r="${lidar_size}" h="${lidar_size}"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${chassis_height/2 + lidar_size/2}" rpy="0 0 0"/>
  </joint>

  <!-- ==================== CAMERA SENSOR ==================== -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${camera_size} ${camera_size*2} ${camera_size}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <xacro:box_inertia m="0.05" x="${camera_size}" y="${camera_size*2}" z="${camera_size}"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${chassis_length/2} 0 ${chassis_height/4}" rpy="0 0 0"/>
  </joint>

  <link name="camera_optical_link"/>
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_optical_link"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- ==================== GAZEBO COLORS ==================== -->
  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>
  <gazebo reference="front_left_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="front_right_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="rear_left_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="rear_right_wheel_link">
    <material>Gazebo/Black</material>
  </gazebo>
  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="camera_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- ==================== GAZEBO DIFFERENTIAL DRIVE PLUGIN ==================== -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>front_left_wheel_joint</left_joint>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <right_joint>rear_right_wheel_joint</right_joint>
      <wheel_separation>${wheel_y_offset * 2}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <odom_publish_frequency>50</odom_publish_frequency>
      <topic>cmd_vel</topic>
      <odom_topic>odom</odom_topic>
      <tf_topic>tf</tf_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>base_footprint</child_frame_id>
    </plugin>
  </gazebo>

  <!-- ==================== GAZEBO JOINT STATE PUBLISHER ==================== -->
  <gazebo>
    <plugin filename="gz-sim-joint-state-publisher-system" name="gz::sim::systems::JointStatePublisher">
      <joint_name>front_left_wheel_joint</joint_name>
      <joint_name>front_right_wheel_joint</joint_name>
      <joint_name>rear_left_wheel_joint</joint_name>
      <joint_name>rear_right_wheel_joint</joint_name>
    </plugin>
  </gazebo>

  <!-- ==================== LIDAR SENSOR PLUGIN ==================== -->
  <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_lidar">
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <visualize>true</visualize>
      <topic>scan</topic>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </lidar>
    </sensor>
  </gazebo>

  <!-- ==================== CAMERA SENSOR PLUGIN ==================== -->
  <gazebo reference="camera_link">
    <sensor name="camera" type="camera">
      <always_on>true</always_on>
      <update_rate>30</update_rate>
      <visualize>true</visualize>
      <topic>camera</topic>
      <camera>
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>100</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
    </sensor>
  </gazebo>

</robot>
